# Generated by Django 3.0 on 2022-03-09 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время создание')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновление')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаление')),
                ('full_name', models.CharField(max_length=20, verbose_name='Аккаунт')),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Акакаунт',
                'verbose_name_plural': 'Аккаунты',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время создание')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновление')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаление')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время создание')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновление')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаление')),
                ('age', models.IntegerField(verbose_name='Возраст студета')),
                ('gpa', models.FloatField(verbose_name='Средняя оценка')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Account', verbose_name='Аккаунт')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ('account',),
            },
        ),
        migrations.CreateModel(
            name='Proffessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время создание')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновление')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаление')),
                ('full_name', models.CharField(max_length=20, verbose_name='полное имя')),
                ('topic', models.CharField(choices=[{'Java', 'JAVA'}, {'python', 'Python'}, {'Typescript', 'JavaScript'}, {'TypeScript', 'Ruby'}, {'Goland', 'Ruby'}, {'Golang', 'Sql'}, {'SQL', 'swift'}, {'Swift', 'swift'}], default='Java', max_length=20, verbose_name='предмет')),
                ('students', models.ManyToManyField(to='firstapp.Student')),
            ],
            options={
                'verbose_name': 'Проффессор',
                'verbose_name_plural': 'Проффессоры',
                'ordering': ('full_name',),
            },
        ),
    ]
