# Generated by Django 3.0 on 2022-02-04 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_group_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Account', verbose_name='Аккаунт'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='firstapp.Group', verbose_name='Группа'),
        ),
    ]
