# Generated by Django 4.0.2 on 2022-02-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20220204_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proffessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20, verbose_name='полное имя')),
                ('topic', models.CharField(choices=[{'JAVA', 'java'}, {'Pthon', 'python'}, {'typescript', 'JavaScript'}, {'TypeScript', 'ruby'}, {'goland', 'Ruby'}, {'sql', 'Golang'}, {'SQL', 'swift'}, {'swift', 'Swift'}], default='java', max_length=20, verbose_name='предмет')),
                ('students', models.ManyToManyField(to='firstapp.Student')),
            ],
        ),
    ]
