# Generated by Django 3.0 on 2022-02-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_proffessor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proffessor',
            options={'ordering': ('full_name',), 'verbose_name': 'Проффессор', 'verbose_name_plural': 'Проффессоры'},
        ),
        migrations.AlterField(
            model_name='proffessor',
            name='topic',
            field=models.CharField(choices=[{'JAVA', 'Java'}, {'python', 'Python'}, {'JavaScript', 'Typescript'}, {'Ruby', 'TypeScript'}, {'Ruby', 'Goland'}, {'Golang', 'Sql'}, {'swift', 'SQL'}, {'Swift', 'swift'}], default='Java', max_length=20, verbose_name='предмет'),
        ),
    ]
