# Generated by Django 3.0 on 2022-02-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20220211_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-11', verbose_name='время создание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='datetime_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время удаление'),
        ),
        migrations.AddField(
            model_name='account',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='время обновление'),
        ),
        migrations.AddField(
            model_name='proffessor',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-11', verbose_name='время создание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proffessor',
            name='datetime_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время удаление'),
        ),
        migrations.AddField(
            model_name='proffessor',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='время обновление'),
        ),
        migrations.AddField(
            model_name='student',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-11', verbose_name='время создание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='datetime_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время удаление'),
        ),
        migrations.AddField(
            model_name='student',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='время обновление'),
        ),
        migrations.AlterField(
            model_name='group',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время создание'),
        ),
        migrations.AlterField(
            model_name='group',
            name='datetime_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время удаление'),
        ),
        migrations.AlterField(
            model_name='group',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='время обновление'),
        ),
    ]
