# Generated by Django 3.0 on 2022-03-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_root',
            new_name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_stuff',
        ),
    ]
